Update ui_template.html
alex-controlx/red-dashboard-svg-control pull request #8
Opened 2021-07-30 23:21 UTC by JuanHauara

2021-07-31 13:17 UTC, alex-controlx requested changes
Hi Juan, I'm glad you found it useful. Could you change comments to english please?

2021-08-15 16:08 UTC, JuanHauara commented
Hello, yes of course.

2021-08-15 16:24 UTC, JuanHauara commented
Done

2021-11-05 05:25 UTC, alex-controlx commented
Hi Juan, just noticed that it wasn't addressed.

I cannot Merge the pull request as the proposed changes violate the design functionality. I'll try explain below, however correct me if I'm wrong.

In your proposed code line 117 you added `cxTypeParts`. It isn't correct as the topic in the message should not have "parts". For example if I have a SVG group `<g id="T-101_level@cx_move,cx_hide">...</g>` then a message from upstream node cannot be `{"payload":{"x":0,"y":0,"deg":17},"topic":"T-101_level@cx_move,cx_hide"}` it needs to be `{"payload":{"x":0,"y":0,"deg":17},"topic":"T-101_level@cx_move"}` or `{"payload":true,"topic":"T-101_level@cx_hide"}`

I'm working on version 2 where I'm going away from using `topic` property and will add `cxId` and `cxClass` properties.

2021-11-11 17:05 UTC, JuanHauara commented
ok I understand. I will be attentive to the new version. Thanks.

2021-11-11 17:05 UTC, closed without merging